'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' SpellCheckOptionsForm class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class SpellCheckOptionsForm

	''' <summary>
	''' pnlOptions control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected pnlOptions As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

	''' <summary>
	''' chkbUpperCase control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkbUpperCase As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' chkbMixedCase control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkbMixedCase As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' chkbNumbers control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkbNumbers As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' chkbEmails control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkbEmails As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' chkbUrls control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkbUrls As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' chkbTags control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkbTags As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' pnlLanguageSelection control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected pnlLanguageSelection As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

	''' <summary>
	''' comboLanguage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected comboLanguage As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' btnOK control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnOK As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnCancel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
