'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' SpellCheckForm class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class SpellCheckForm

	''' <summary>
	''' SCCheckedDiv control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCCheckedDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	''' <summary>
	''' btnIgnore control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnIgnore As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnIgnoreAll control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnIgnoreAll As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnAddToDictionary control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnAddToDictionary As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' ChangeToPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ChangeToPanel As Global.DevExpress.Web.ASPxPanel.ASPxPanel

	''' <summary>
	''' PanelContent1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

	''' <summary>
	''' txtChangeTo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected txtChangeTo As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

	''' <summary>
	''' SCSuggestionsListBox control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCSuggestionsListBox As Global.DevExpress.Web.ASPxEditors.ASPxListBox

	''' <summary>
	''' btnChange control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnChange As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnChangeAll control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnChangeAll As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnOptions control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnOptions As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnClose control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnClose As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
